channels:
- defaults
dependencies:
- python=3.6.6
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/15587761
  - azureml-defaults==0.1.0.15587761
  - azureml-pipeline-wrapper==0.1.0.15587761
  - torch==1.4.0
  - scikit-learn
  - tqdm
name: project_environment