channels:
- defaults
dependencies:
- python=3.6.8
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/19783628
  - azureml-defaults==0.1.0.19783628
  - azureml-pipeline-wrapper==0.1.0.19783628
name: project_environment
