channels:
- defaults
dependencies:
- python=3.6.6
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/15541990
  - azureml-defaults==0.1.0.15541990
  - azureml-pipeline-wrapper==0.1.0.15541990
  - spacy==2.1.9
  - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz
  - allennlp==0.9.0
  - matplotlib
  - scikit-learn
  - torch
  - torchvision
name: project_environment


